---
- name: Create temporary directory to store related files
  tempfile:
    state: directory
    suffix: keycloak
  register: keycloak_temp_dir
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Interpolate Ansible variables
  template:
    src: docker-compose.yml.j2
    dest: "{{ keycloak_temp_dir.path }}/docker-compose.yml"
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Deploy keycloak in Swarm
  command: 'docker stack deploy --compose-file {{ keycloak_temp_dir.path }}/docker-compose.yml keycloak'
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Record Traefik DNS
  ara_record:
    key: "keycloak_host"
    value: "http://{{ keycloak_host }}"
    type: url
  tags:
    - skip_ansible_lint